GOOGLE_CLIENT_ID = "..."
GOOGLE_CLIENT_SECRET = "..."
MICROSOFT_CLIENT_ID = "..."
MICROSOFT_CLIENT_SECRET = "..."
MICROSOFT_TENANT_ID = "common"
OAUTH_REDIRECT_URI = "https://elixir-study.streamlit.app"
